<link rel="stylesheet" type="text/css" media="screen" href="css/all.css">
<link rel="stylesheet" type="text/css" media="screen" href="css/index.css">
<link rel="stylesheet" type="text/css" media="screen" href="css/navbar.css">
<link rel="stylesheet" type="text/css" media="screen" href="css/prestation.css">
<link rel="stylesheet" type="text/css" media="screen" href="css/collaboration.css">
<link rel="stylesheet" type="text/css" media="screen" href="css/projet.css">