<link rel="stylesheet" type="text/css" media="screen" href="css/all.css">
<link rel="stylesheet" type="text/css" media="screen" href="css/index.css">
<link rel="stylesheet" type="text/css" media="screen" href="css/navbar.css">
<link rel="stylesheet" type="text/css" media="screen" href="css/prestation.css">
<link rel="stylesheet" type="text/css" media="screen" href="css/collaboration.css">
<link rel="stylesheet" type="text/css" media="screen" href="css/projet.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<link rel="stylesheet" type="text/css" media="screen" href="css/footer.css">
